"""first generated commit

Revision ID: 1b1b969f1575
Revises: 4bcc9539db53
Create Date: 2022-10-16 15:16:54.502203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1b969f1575'
down_revision = '4bcc9539db53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('testid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('testid', name='test_pkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
