"""Upgraded ORM Entities to latest models

Revision ID: 71d72a921a92
Revises: c58aab59fea1
Create Date: 2022-11-03 01:57:24.061036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d72a921a92'
down_revision = 'c58aab59fea1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sent', sa.DateTime(), nullable=False),
    sa.Column('content', sa.String(length=512), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('chatroom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chatroom_id'], ['chatrooms.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_chatroom_join_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chatrooms_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chatrooms_id'], ['chatrooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'chatrooms_id')
    )
    op.add_column('users', sa.Column('pw', sa.String(), nullable=False))
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('inactive', sa.DateTime(), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('users', 'inactive')
    op.drop_column('users', 'admin')
    op.drop_column('users', 'pw')
    op.drop_table('user_chatroom_join_table')
    op.drop_table('messages')
    op.drop_table('chatrooms')
    # ### end Alembic commands ###
