"""Updates to the User model

Revision ID: 7c687f15a1e3
Revises: bab86a03595d
Create Date: 2022-11-03 19:43:46.715052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c687f15a1e3'
down_revision = 'bab86a03595d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.drop_constraint('users_name_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'name')
    op.drop_column('users', 'pw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pw', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_name_key', 'users', ['name'])
    op.drop_column('users', 'password')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
